web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  dockerfile: ./Dockerfile-development
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - db
  env_file: .env
  environment:
    - API_STAGE=dev

test:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  dockerfile: ./Dockerfile-development
  volumes:
    - .:/app
  ports:
    - "4000:3000"
  links:
    - dbtest
  env_file: .env
  environment:
    - API_STAGE=dev
    - RAILS_ENV=test

db:
  image: postgres

dbtest:
  image: postgres

webproduction:
  build: .
  ports:
    - "3000:80"
  links:
    - db
  env_file: .env
  environment:
    - RACK_ENV=production
    - API_STAGE=prod
    - RAILS_ENV=production

webstaging:
  build: .
  dockerfile: ./Dockerfile-development
  ports:
    - "3000:80"
  links:
    - db
  env_file: .env
  environment:
    - RACK_ENV=production
    - RAILS_ENV=staging
    - API_STAGE=staging
